app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
    path('add/', views.add),
    path('display/', views.display), # aqui usar /<int:id>
    path('edit/', views.edit), # aqui usar /<int:id>
    path('delete/', views.delete), # aqui usar /<int:id>
    path('other/', views.other), # aqui usar /<int:id>


    path('registro/', views.registro),
    path('login/', views.login), 
    path('logout/', views.logout),
    
]

ecommerce/urls.py
from django.urls import path     
from . import views_forms
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ecommerce'

urlpatterns = [
    path('', views_forms.mainPage, name='mainPage' ),
    path('products/<str:size>', views_forms.productBySize, name='productBySize'),
    path('logout/', views_forms.logout, name='logout' ),
    path('products/addToShoppingCart/<int:id>', views_forms.addToShoppingCart, name='addToShoppingCart'),
    path('shoppingCart/empty', views_forms.shoppingCartempty, name='shoppingCartempty'),
    path('shoppingCart/', views_forms.shoppingCart, name='shoppingCart'),
    path('shoppingCart/buy', views_forms.buy, name='buy'),
    path('shoppingCart/delete/<int:id>', views_forms.deleteProductFromCart, name='deleteProductCart'),
    path('products/', views_forms.productGrid, name='productGrid'),
    path('products/<str:category>/', views_forms.productGridByCat, name='productGridByCat'),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pharm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pharmacy.urls')),
    path('',include('reportes.urls')),
    # path('',include('app.urls')),
    path('',include('ecommerce.urls')),
    path('',include('django.contrib.auth.urls')),


]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pharmacy/urls.py
from django.urls import path
from .import HODViews
from .import pharmacistViews,DoctorViews,views,patient_view,clerkViews
from ecommerce import views_forms
from django.contrib.auth import views as auth_views


urlpatterns=[
    path('',HODViews.adminDashboard,name='admin_dashboard'),
    path('admin_user/patient_form/',HODViews.createPatient,name='patient_form'),
    path('admin_user/all_patients/',HODViews.allPatients,name='all_patients'),
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logoutUser,name='logout'), 
    # path('get_user_details/', views.get_user_details, name="get_user_details"),

    path('admin_user/add_pharmacist/',HODViews.createPharmacist,name='add_pharmacist'),
    path('admin_user/manage_pharmacist/',HODViews.managePharmacist,name='manage_pharmacist'),
    path('admin_user/add_doctor/',HODViews.createDoctor,name='add_doctor'),
    path('admin_user/manage_doctor/',HODViews.manageDoctor,name='manage_doctor'),
    path('admin_user/add_pharmacyClerk/',HODViews.createPharmacyClerk,name='add_pharmacyClerk'),
    path('admin_user/admin_user/manage_pharmacyClerk/',HODViews.managePharmacyClerk,name='manage_pharmacyClerk'),
    path('admin_user/showDrugs/',HODViews.adminShowProductsPage,name='showDrugs'),
    path('admin_user/showDrugs/add',HODViews.addDrug,name='addDrugs'),
    path('adminPage/products/edit/<int:id>', HODViews.editDrug, name='editProd' ),
    path('adminPage/products/delete/<int:id>', HODViews.deleteDrug, name='deleteProd' ),
    path('adminPage/products/detail/<int:id>', HODViews.showProductDetail, name='showProductDetail' ),
    path('adminPage/products/addCategory', HODViews.addCategory, name='addCategory' ),
    path('adminPage/products/editCat/<int:id>', HODViews.editCat, name='editCat' ),
    path('adminPage/products/deleteCat/<int:id>', HODViews.deleteCat, name='deleteCat' ),

    path('admin_user/manage_stock/',HODViews.manageStock,name='manage_stock'),    
    path('admin_user/prescribe_drug/',HODViews.addPrescription,name='prescribe'),
    path('admin_user/edit_patient/<patient_id>/',HODViews.editPatient,name='edit_patient'),
    # path('add_patient_save/',HODViews.editPatientSave,name='edit_patient_save'),

    path('admin_user/delete_patient/<str:pk>/',HODViews.confirmDelete,name='delete_patient'),
    path('admin_user/patient_personalRecords/<pk>/',HODViews.patient_personalRecords,name='patient_record'),
    path('admin_user/delete_prescription/<str:pk>/',HODViews.deletePrescription,name='delete_prescription'),
    path('admin_user/doctor_profile/',DoctorViews.doctorProfile,name='doctor_profile'),
    path('admin_user/hod_profile/',HODViews.hodProfile,name='hod_profile'),
    path('admin_user/delete_doctor/<str:pk>/',HODViews.deleteDoctor,name='delete_doctor'),
    path('admin_user/delete_pharmacist/<str:pk>/',HODViews.deletePharmacist,name='delete_pharmacist'),
    path('admin_user/delete_receptionist/<str:pk>/',HODViews.deletePharmacyClerk,name='delete_clerk'),
    path('admin_user/hod_profile/editAdmin_profile/',HODViews.editAdmin,name='edit-admin'),
    path('admin_user/delete_drug/<str:pk>/',HODViews.deleteDrug,name='delete_drug'),


    path('admin_user/edit_pharmacist/<staff_id>/', HODViews.editPharmacist, name="edit_pharmacist"),
    path('admin_user/edit_doctor/<doctor_id>/', HODViews.editDoctor, name="edit_doctor"),
    path('admin_user/edit_receptionist/<clerk_id>/', HODViews.editPharmacyClerk, name="edit_clerk"),
    path('admin_user/edit_drug/<pk>/', HODViews.editStock, name="edit_drug"),
    path('admin_user/receive_drug/<pk>/', HODViews.receiveDrug, name="receive_drug"),
    path('admin_user/reorder_level/<str:pk>/', HODViews.reorder_level, name="reorder_level"),
    path('admin_user/drug_details/<str:pk>/', HODViews.drugDetails, name="drug_detail"),
    path('patient_feedback_message/', pharmacistViews.patient_feedback_message, name="patient_feedback_message"),
    path('patient_feedback_message_reply/', pharmacistViews.patient_feedback_message_reply, name="patient_feedback_message_reply"),
    path('admin_user/delete_patient_feedback/<str:pk>/', pharmacistViews.deletefeedback, name="delete_fed"),

        path('delete_details/<str:pk>/', pharmacistViews.deleteDispense4, name="del_disp"),



    #Pharmacist
    path('pharmacist_home/',pharmacistViews.pharmacistHome,name='pharmacist_home'),
    path('pharmacist_manage_patients/',pharmacistViews.managePatientsPharmacist,name='manage_patient_pharmacist'),
    path('manage_disp/<pk>/',pharmacistViews.manageDispense,name='pharmacist_disp'),
#    path('manage_dispe/<str:pk>/',pharmacistViews.dispenseDrug,name='pharm_disp'),
    # path('manage_stock_form/<str:pk>/',pharmacistViews.dispense,name='pharm_disp2'),
    path('staff_profile/',pharmacistViews.userProfile,name='pharmacist_profile'),

    path('manage_stock2/',pharmacistViews.manageStock,name='manage_stock2'),    
    path('manage_prescrip/',pharmacistViews.managePrescription,name='pharmacist_prescription'),
    path('pharmacist_user/drug_details/<str:pk>/', pharmacistViews.drugDetails, name="drug_detail2"),



    #Doctor
    path('doctor_home/',DoctorViews.doctorHome,name='doctor_home'),
    path('manage_patients/',DoctorViews.managePatients,name='manage_patient_doctor'),
    path('doctor_prescribe_drug/<str:pk>/',DoctorViews.addPrescription,name='doctor_prescribe2'),
    path('patient_personalDetails/<str:pk>/',DoctorViews.patient_personalDetails,name='patient_record_doctor'),
    path('manage_prescription_doctor/',DoctorViews.managePrescription,name='manage_precrip_doctor'),
    path('doctor_prescribe_delete/<str:pk>/',DoctorViews.deletePrescription,name='doctor_prescrip_delete'),
    path('doctor_prescribe_edit/<str:pk>/',DoctorViews.editPrescription,name='doctor_prescrip_edit'),
    path('receta/<int:pk>',DoctorViews.receta_pdf,name='receta_pdf'),
    #Patients
    path('patient_profile/',patient_view.patientProfile,name='patient_profile'),
    path('patient_home/',patient_view.patientHome,name='patient_home'),
    path('patient_feedback/',patient_view.patient_feedback,name='patient_feedback'),
    path('staff_feedback_save/', patient_view.patient_feedback_save, name="patient_feedback_save"),
    path('taken_home/',patient_view.patient_dispense3,name='taken_home'),
    path('delete_patient_feedback2/<str:pk>/',patient_view.Patientdeletefeedback, name="delete_fed2"),
    path('delete_dispen/',patient_view.myPrescriptionDelete,name='taken_delete'),
    path('shoppingCart/empty', views_forms.shoppingCartempty, name='shoppingCartempty'),
    path('products/', views_forms.productGrid, name='productGrid'),

    #Receptionist
    path('receptionist_profile/',clerkViews.receptionistProfile,name='clerk_profile'),
    path('receptionist_home/',clerkViews.clerkHome,name='clerk_home'),
    path('receptionist/patient_form/',clerkViews.createPatient,name='patient_form2'),
    path('receptionist/all_patients/',clerkViews.allPatients,name='all_patients2'),
    path('receptionist/edit_patient/<patient_id>/',clerkViews.editPatient,name='edit_patient_clerk'),
    path('receptionist/patient_personalRecords/<str:pk>/',clerkViews.patient_personalRecords,name='patient_record_clerk'),
    path('receptionist/delete_patient/<str:pk>/',clerkViews.confirmDelete,name='delete_patient_clerk'),
    # path('receptionist/dispense_drug/<str:pk>/',pharmacistViews.dispenseDrug,name='dispense_drug'),


  
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name="reset_password"),

    path('reset_password_sent/',auth_views.PasswordResetDoneView
    .as_view(template_name="password_reset_sent.html"),name="password_reset_done"),
    
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView
    .as_view(template_name="password_reset_form.html"),name="password_reset_confirm"),



    

   path('reset_password_complete/',auth_views.PasswordResetCompleteView
    .as_view(template_name="password_reset_done.html"),name="password_reset_complete"),
]

ecommerce/models.py
from django.db import models
from pharmacy.models import CustomUser, Product
from django.utils import timezone


class Boleta(models.Model):

    total = models.DecimalField(decimal_places=2, max_digits=6)
    totalDesc = models.DecimalField(decimal_places=2, max_digits=6, default=0)
    totalOpGravada = models.DecimalField(decimal_places=2, max_digits=6)
    totalIGV = models.DecimalField(decimal_places=2, max_digits=6)
    precioEnvio = models.DecimalField(decimal_places=2, max_digits=6, default = 10)
    #detalleBoleta=models.ManyToManyField(BoletaDetalle, related_name='carritos')
    users = models.ForeignKey(CustomUser, related_name='usuarios2', on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pagado = models.BooleanField(default=False)

    def __str__ (self):
        return f'{self.users} - {self.pagado}'


class BoletaDetalle(models.Model):
    
    precioUni = models.DecimalField(decimal_places=2, max_digits=6, default=0)
    subtotal = models.DecimalField(decimal_places=2, max_digits=6)
    descuento = models.DecimalField(decimal_places=2, max_digits=6, default=0)
    opGravada = models.DecimalField(decimal_places=2, max_digits=6)
    igv = models.DecimalField(decimal_places=2, max_digits=6)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(CustomUser, related_name='usuarios', on_delete=models.CASCADE)
    productos = models.ForeignKey(Product, related_name='boletaDetalle', on_delete=models.CASCADE, default=0)
    cantidad = models.IntegerField(default=1, null=False)
    estado = models.BooleanField(default=False)
    boleta = models.ForeignKey(Boleta, related_name='boletas', on_delete=models.CASCADE, default =1)
    
    def __str__ (self):
        return f'{self.usuario} - {self.productos} - {self.cantidad} - {self.boleta.id}'

ecommerce/templates/ecommerce/addProduct.html
{% extends "ecommerce/indexAdmin.html" %}
{% block title%}Añadir Producto{%endblock%}
{% block content%}

<h1 class="text-center">Agregar producto</h1>
<div class="d-flex justify-content-between p-5">
    
    <form class="container d-flex flex-column w-50 " action="" method="post" enctype = "multipart/form-data" >
        {% csrf_token %}
        {{ ProductForm.non_field_errors }}

        {% for field in ProductForm %}
        <div class="mb-3 row fs-4">
            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9 fs-4">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="container fs-3 d-flex justify-content-center">
            <div class="d-flex ">
                <a href="" class="btn btn-light m-1">Cancel</a>
            </div>
            <div class="d-flex ">
                <form action="" method="post">
                    <button class="btn btn-warning m-1" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </form>
    {% load static %}
    <img class="halfImage " src="{% static 'img/babyClothesAdd.jpg' %}" alt="Error de carga, por favor actualizar" >
</div>


{% endblock %}

ecommerce/templates/ecommerce/addUser.html
{% extends "ecommerce/indexAdmin.html" %}
{% block title%}Añadir Usuario{%endblock%}
{% block content%}

<h1 class="text-center">Agregar Usuario</h1>
<div class="d-flex justify-content-between p-5">

    <form class="container d-flex flex-column w-50 " action="" method="post">
        {% csrf_token %}
        {{ userForm.non_field_errors }}

        {% for field in userForm %}
        <div class="mb-3 row fs-4">
            <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
            <div class="col-sm-9 fs-4">
                {{ field }}
            </div>

            {% if field.errors %}

            <div class="alert alert-danger mt-2" role="alert">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>

            {% endif %}

            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
        {% endfor %}
        <div class="d-flex flex-column">
            <div class="container fs-3 d-flex justify-content-center">
                <div class="d-flex ">
                    <a href="{% url 'baby:showUsers'%}" class="btn btn-light m-1">Cancel</a>
                </div>
                <div class="d-flex ">
                    <form action="" method="post">
                        <button class="btn btn-warning m-1" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </form>
    {% load static %}
    <img class="halfImage " src="{% static 'img/babyClothesAdd.jpg' %}" alt="Error de carga, por favor actualizar">
</div>


{% endblock %}

ecommerce/templates/ecommerce/products.html
{% extends "ecommerce/index.html" %}
{% block title%}FarmaBot{%endblock%}
{% block content%}

<div class="container d-flex flex-column">
    <div class="d-md-flex align-items-md-center">
        <div class="h3 mt-3">Medicamentos</div>
        <div class="ml-auto d-flex align-items-center views"> <span class="btn text-success">
                <span class="fas fa-th px-md-2 px-1"></span>
                <span>Grid view</span> </span>
            <span class="btn"> </span>
            <span class="green-label px-md-2 px-1">{{allProductCount}}</span> <span class="text-muted">Products</span>
        </div>
    </div>
    <div class="d-flex flex-row">
        <div class="content py-md-0 py-3">
            <section id="sidebar">
                <div class="py-3">
                    <h5 class="font-weight-bold">Categorias</h5>
                    <ul class="list-group">
                        <li
                        class=" text-decoration-none list-group-item list-group-item-action d-flex justify-content-between align-items-center category">
                        <a class="color-dark" href="{% url 'ecommerce:productGrid'%}">Todos</a> <span class="badge badge-primary badge-pill">{{allProductCount}}</span> </li>
                        {% for cat in categories %}
                        <li
                            class="list-group-item list-group-item-action d-flex justify-content-between align-items-center category">
                            <a class="text-decoration-none" href="{% url 'ecommerce:productGridByCat' category=cat.name %}">{{cat.name}}</a>
                            <span class="badge badge-primary badge-pill">{{cat.cantProd}}</span> </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="py-3">
                    <h5 class="font-weight-bold">Brands</h5>
                    <form class="brand">
                        <div class="form-inline d-flex align-items-center py-1"> <label class="tick">Royal Fields <input
                                    type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-1"> <label class="tick">Crasmas Fields
                                <input type="checkbox" checked> <span class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-1"> <label class="tick">Vegetarisma Farm
                                <input type="checkbox" checked> <span class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-1"> <label class="tick">Farmar Field Eve
                                <input type="checkbox"> <span class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-1"> <label class="tick">True Farmar Steve
                                <input type="checkbox"> <span class="check"></span> </label> </div>
                    </form>
                </div>
                <div class="py-3">
                    <h5 class="font-weight-bold">Rating</h5>
                    <form class="rating">
                        <div class="form-inline d-flex align-items-center py-2"> <label class="tick"><span
                                    class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                    class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                    class="fas fa-star"></span> <input type="checkbox"> <span class="check"></span>
                            </label> </div>
                        <div class="form-inline d-flex align-items-center py-2"> <label class="tick"> <span
                                    class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                    class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <input type="checkbox"> <span
                                    class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-2"> <label class="tick"><span
                                    class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                    class="fas fa-star"></span> <span class="far fa-star px-1 text-muted"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <input type="checkbox"> <span
                                    class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-2"> <label class="tick"><span
                                    class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <input type="checkbox"> <span
                                    class="check"></span> </label> </div>
                        <div class="form-inline d-flex align-items-center py-2"> <label class="tick"> <span
                                    class="fas fa-star"></span> <span class="far fa-star px-1 text-muted"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <span
                                    class="far fa-star px-1 text-muted"></span> <input type="checkbox"> <span
                                    class="check"></span> </label> </div>
                    </form>
                </div>
            </section> <!-- Products Section -->
            <section id="products">
                <div class="container py-3">
                    <div class="row d-flex flex-wrap">
                        {% for product in productos %}
                        <div class="col-lg-4 col-md-6 col-sm-10 offset-md-0 offset-sm-1 mb-1">
                            <div class="card"> <img class="card-img-top"
                                    src="{{ product.img.url }}">
                                <div class="card-body">
                                    <h6 class="font-weight-bold pt-1">{{ product.name }}</h6>
                                    <div class="text-muted description">{{product.description}}</div>
                                    <div class="d-flex align-items-center product"> <span class="fas fa-star"></span>
                                        <span class="fas fa-star"></span> <span class="fas fa-star"></span> <span
                                            class="fas fa-star"></span> <span class="far fa-star"></span>
                                    </div>
                                    <div class="d-flex align-items-center justify-content-between pt-3">
                                        <div class="d-flex flex-column">
                                            <div class="h6 font-weight-bold">Tienda: S/.{{product.price}}</div>
                                            <div class="text-muted rebate">Internet: S/.{{product.price}}</div>
                                            <form action="{% url 'ecommerce:addToShoppingCart' id=product.id %}" method="post" class="d-flex justify-content-center">
                                                {% csrf_token %}
                                                <select class="form-select littleSelect w-100" aria-label="Default select example" name="cantidad">
                                                    <option selected value="1">1</option>
                                                    <option value="2">2</option>
                                                    <option value="3">3</option>
                                                    <option value="4">4</option>
                                                    <option value="5">5</option>
                                                </select>
                                                <button class="btn btn-info px-4 " type="submit"><i class="fa-solid fa-cart-plus"></i> Agregar</button>
                                            </form>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
        </div>
        </section>
    </div>
</div>
{% endblock %}

ecommerce/templates/ecommerce/shoppingCart.html
{% extends "ecommerce/index.html" %}
{% block title%}Carrito de Compras{%endblock%}
{% block content%}
<div class="d-flex justify-content-end ">
    <div class="p-5 vw-100">
        <div class="d-flex justify-content-between align-items-center mb-5">
            <h1 class="fw-bold mb-0 text-black">Carrito de compras</h1>
            <h6 class="mb-0 text-muted">3 items</h6>
        </div>
        {% for product in cart %}
        <hr class="my-4">
        <div class="row mb-4 d-flex justify-content-between align-items-center">
            <div class="col-md-2 col-lg-2 col-xl-2">
                <img src="{{ product.productos.img.url }}"
                    class="img-fluid rounded-3" alt="Cotton T-shirt">
            </div>
            <div class="col-md-3 col-lg-3 col-xl-3">
                <h6 class="text-muted text-capitalize">{{product.productos.dosageForm.name}}</h6>
                <h6 class="text-muted text-capitalize">Dosis: {{product.productos.dose}}</h6>
                <h6 class="text-black mb-0 text-capitalize">{{product.productos.name}}</h6>
                
            </div>
            <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <h6>Cantidad: {{product.cantidad}}</h6>
                <!--<button class="btn btn-link px-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                    <i class="fas fa-minus"></i>
                </button>

                <input id="form1" min="0" name="quantity" value="1" type="number"
                    class="form-control form-control-sm" />

                <button class="btn btn-link px-2"
                    onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                    <i class="fas fa-plus"></i>
                </button>-->
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h6 class="mb-0">S/. {{product.subtotal}}</h6>
            </div>
            <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <form action="{% url 'ecommerce:deleteProductCart' id=product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="text-muted btn btn-link"><i class="fas fa-times"></i></button>
                </form>
            </div>
        </div>
        {% endfor %}
        
        <div class="pt-5">
            <h6 class="mb-0"><a href="{% url 'ecommerce:productGrid' %}" class="text-body"><i class="fas fa-long-arrow-alt-left me-2"></i>Back to
                    shop</a></h6>
        </div>
    </div>


    <div class="col-lg-4 bg-grey h-100">
        <div class="p-5">
            <h3 class="fw-bold mb-4 mt-1 pt-1">Resumen de Compra</h3>
            {% for product in cart %}
            <hr class="my-1">
            <div class="d-flex justify-content-between mb-2 align-items-center">
                <div>
                    <p class="text-capitalize my-2">{{product.productos.dosageForm.name}}</p>
                    <p class="text-capitalize my-2">{{product.productos.name}}</p>
                    
                </div>
                <p>Cantidad: {{product.cantidad}}</p>
                <p>S/.{{product.subtotal}}</p>
            </div>
            {% endfor %}

            <h5 class="text-capitalize mb-3">Costo de Envio</h5>

            <div class="mb-4 pb-2">
                <p class="fs-4">Delivery Base - S/.10</p>
            </div>

            <h5 class="text-uppercase mb-3">Give code</h5>

            <div class="mb-5">
                <div class="form-outline">
                    <input type="text" id="form3Examplea2" class="form-control form-control-lg" />
                    <label class="form-label" for="form3Examplea2">Enter your code</label>
                </div>
            </div>

            <hr class="my-4">

            <div class="d-flex flex-column justify-content-between mb-3">
                <h5 class="text-uppercase">Detalle Precio</h5>
                <div class="d-flex my-0 justify-content-between">
                    <p class="fs-5">Descuento:</p><p class="fs-5 ">S/.{{descuento}}</p>
                </div>
                <div class="d-flex my-0 justify-content-between">
                    <p class="fs-5">Op.Gravada:</p><p class="fs-5 ">S/.{{op_gravada}}</p>
                </div>
                <div class="d-flex my-0 justify-content-between">
                    <p class="fs-5">IGV:</p><p class="fs-5 ">S/.{{igv}}</p>
                </div>
                <div class="d-flex my-0 justify-content-between">
                    <h5 class="fs-5">Monto Final:</h5><h5 class="fs-5 ">S/.{{subtotal}}</h5>
                </div>
            </div>
            <form action="{% url 'ecommerce:buy' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-dark btn-block btn-lg" data-mdb-ripple-color="dark">Comprar</button>
            </form>
            

        </div>
    </div>
</section>


{% endblock %}